INSERT INTO Recompense (nomRecompense, idPays)
VALUES ('Prix du film allemand (Deutscher Filmpreis ou "Lolas") de Deutsche Filmakademie', 1),
('Ours d\'or (Goldener Bär) du Festival international du film de Berlin (Berlinale)', 1),
('Prix du court métrage (Deutsche Kurzfilmpreis) du Gouvernement fédéral', 1),
('Prix Ernst Lubitsch du Club der Berliner Filmjournalisten', 1),
('Prix de l\'association des critiques allemands de film (Preise des Verbandes der Deutschen Filmkritik)', 1),
('Prix des réalisateurs allemands (Deutscher Darstellerpreis)', 1),
('Prix du film bavarois (Bayerischer Filmpreis) Land de Bavière (Munich)', 1),
('Prix de la critique (Preis der Hamburger Filmkritik) du Festival du film de Hambourg', 1),
('Prix allemand du film indépendant (German Independence Award) du Festival international du film d\'Oldenbourg', 1),
('Prix du box office en Allemagne (Box Office Germany Award ou "Bogey Awards")', 1),
('Prix des scénaristes allemands (Deutscher Drehbuchpreis)', 1),
('Prix du film brêmois (Bremer Filmpreis) Land de Brême', 1),
('Prix des acteurs allemands (Deutscher Schauspielerpreis)', 1),
('Prix du film autrichien (Österreichischer Filmpreis) de l\'Akademie des Österreichischen Films', 2),
('Prix du film viennois (Wiener Filmpreis) du Festival international du film de Vienne (Viennale)', 2),
('Âge d\'or de la Cinémathèque royale de Belgique et du musée du cinéma de Bruxelles', 3),
('Magritte du cinéma de l\'Académie André Delvaux', 3),
('Grand prix de l\'Union de la critique de cinéma', 3),
('Prix André-Cavens de l\'Union de la critique de cinéma', 3),
('Grand prix et Prix Humanum de l\'Union de la presse cinématographique belge', 3),
('Grand prix du Festival international du film de Flandre-Gand', 3),
('Corbeau d\'or du Festival international du film fantastique de Bruxelles', 3),
('Grand prix du Festival international du film d\'amour de Mons', 3),
('Prix Joseph-Plateau du Festival international du film de Flandre-Gand', 3),
('Bayard d\'or du Festival international du film francophone de Namur', 3),
('Prix du cinéma flamand (Ensors) du Festival du film d\'Ostende', 3),
('Prix Robert de la Danmarks Film Akademi (Copenhague)', 7),
('Prix Bodil (Bodilprisen) de la Filmedarbejderforeningen', 7),
('Prix Riber (Riberprisen) du court métrage de l\'université d\'Aalborg', 7),
('Prix Nordisk Film (Nordisk Film Prisen) de la société Nordisk Film', 7),
('Grand prix du Festival international du film d\'Odense', 7),
('Prix du public (Audience Award) du NatFilm Festival', 7),
('Cygne d\'or (Golden Swan) du Festival international du film de Copenhague', 7),
('Prix CPH:DOX (CPH:DOX Award) du Festival international du film documentaire de Copenhague', 7),
('Grand prix du nouveau talent (New Talent Grand Pix) du Festival international du film de Copenhague', 7),
('Prix Goya (Premios Goya) de l\'Academia de las Artes y las Ciencias Cinematográficas de España', 8),
('Prix Gaudí (Premis Gaudí) de l\'Acadèmia del Cinema Català (Barcelone)', 8),
('Prix ACCEC (Premis ACCEC) de l\'Associació Catalana de Crítics i Escriptors Cinematogràfics de Catalunya', 8),
('prix ADIRCAE (Premios ADIRCAE) de l\'Asamblea de Directores Realizadores Cinematográficos y Audiovisuales de España', 8),
('Prix Ondas (Premios Ondas) de la Radio Barcelona', 8),
('Coquille d\'or (Urrezko Maskorra ou Concha de Oro) du Festival international du film de Saint-Sébastien', 8),
('Prix Jussi de Filmiaura (Helsinki)', 10),
('Prix national de la cinématographie du Centre pour la promotion des arts', 10),
('Étoile de cristal de l\'Académie du cinéma', 11),
('César du cinéma de l\'Académie des arts et techniques du cinéma', 11),
('Lumières de la presse internationale de l\'Académie des Lumières', 11),
('Prix Louis-Delluc', 11),
('Prix Méliès du Syndicat français de la critique de cinéma', 11),
('Prix Jean-Vigo', 11),
('Prix Jean-Gabin', 11),
('Prix Romy-Schneider', 11),
('Étoiles d\'or de l\'Académie de la presse du cinéma français', 11),
('Globe de cristal (jury d\'écrivains)', 11),
('Prix Patrick-Dewaere', 11),
('Prix Saint-Germain (jury d\'écrivains)', 11),
('Trophée Anne-Sophie Deval', 11),
('Talents Cannes', 11),
('Bidets d\'or de l\'Académie des Bidets d\'or', 11),
('Gérard du cinéma', 11),
('Palme d\'or du Festival de Cannes', 11),
('Cristal d\'Annecy du Festival international du film d\'animation d\'Annecy', 11),
('Grand prix du Festival international du film fantastique d\'Avoriaz', 11),
('Montgolfière d\'or du Festival des trois continents (Nantes)', 11),
('Hitchcock d\'or du Festival du film britannique de Dinard', 11),
('Grand prix du Festival international du film fantastique de Gérardmer', 11),
('Cyclo d\'or du Festival international des cinémas d\'Asie de Vesoul', 11),
('Grand prix du Festival du cinéma américain de Deauville', 11),
('Swann d\'or du Festival du cinéma de Cabourg', 11),
('Prix du public du Champs-Élysées Film Festival', 11),
('Prix du Jury du Champs-Élysées Film Festival', 11),
('Prix du cinéma et de la télévision irlandaise (Irish Film and Television Awards) de l\'Irish Film and Television Academy (Dublin)', 14),
('Prix du cercle des critiques de film de Dublin (Dublin Film Critics\' Circle Awards)', 14),
('Prix Volta (Volta Award) du Festival international du film de Dublin', 14),
('Prix David di Donatello (David) de l\'Accademia del Cinema Italiano (Rome)', 15),
('Ruban d\'argent (Nastri d\'argento) du Sindacato Nazionale Giornalisti Cinematografici Italiani (Rome)', 15),
('Vénus d\'argent (Venere d\'argento) de la Azienda autonoma di soggiorno e turismo (Erice)', 15),
('Globe d\'or (Globo d\'oro) de la Rome Foreign Press Association', 15),
('Prix Filippo Sacchi (Premio Filippo Sacchi) de la Sindacato Nazionale Giornalisti Cinematografici Italiani', 15),
('Lutrin d\'or (Leggio d\'oro) de la Ente Nazionale Democratico di Azione Sociale', 15),
('Lion d\'or (Leone d\'oro) de la Mostra de Venise', 15),
('Griffon d\'or (Grifone d\'oro) du Festival du film de Giffoni', 15),
('Marc Aurèle d\'or (Marc Aurelio d\'oro) du Festival international du film de Rome', 15),
('Chevalier d\'or (Golden Knight) du Golden Knight Malta International (La Valette)', 19),
('Film d\'or (Gouden Film)', 20),
('Veau d\'or (Gouden Kalf) du Festival du cinéma néerlandais d\'Utrecht', 20),
('Tigre d\'or (Tiger Award) du Festival international du film de Rotterdam', 20),
('Aigles du cinéma polonais (Polskie Nagrody Filmowe ou "Orły") de la Polska Akademia Filmowa (Varsovie)', 21),
('Canard d\'or (Złota Kaczka) du magazine Film', 21),
('Passeport de Polityka (Paszport Polityki) de l\'hebdomadaire Polityka', 21),
('Prix Zbigniew Cybulski (Nagroda im. Zbyszka Cybulskiego) du magazine Kino', 21),
('Lions d\'or (Złote Lwy) du Festival du film polonais de Gdynia', 21),
('Corne d\'or (Złoty Róg) du Festival du film de Cracovie', 21),
('Grand prix du Festival international du film de Varsovie', 21),
('Grenouille d\'or (Złota Żaba) du festival Camerimage', 21),
('Jabberwocky d\'or (Złoty Jabberwocky) du festival Festival international du film Etiuda & Anima (Cracovie)', 21),
('Grand prix du Festival international du cinéma indépendant Off Plus Camera (Cracovie)', 21),
('Lion tchèque (Český lev) de la České filmové a televizní akademie', 23),
('Globe de cristal (Křišťálový glóbus) du Festival international du film de Karlovy Vary', 23),
('Prix Gopo (Premiile Gopo) de l\'Association for Romanian Film Promotion', 24),
('Trophée Transylvanie (Trofeul Transilvania) du Festival international du film de Transylvanie (Cluj-Napoca)', 24),
('Cétoine dorée (Guldbagge) de la Svenska Filminstitutet (Stockholm)', 27),
('Prix du dragon (Dragon Awards) du Festival international du film de Göteborg', 27),
('Cheval de bronze (Bronshästen) du Festival international du film de Stockholm', 27);