INSERT INTO Pays (nomPays, clapPays)
VALUES ('Allemagne', 'allemagne.png'),
('Autriche', 'autriche.png'),
('Belgique', 'belgique.png'),
('Bulgarie', 'bulgarie.png'),
('Chypre', 'chypre.png'),
('Croatie', 'croatie.png'),
('Danemark', 'danemark.png'),
('Espagne', 'espagne.png'),
('Estonie', 'estonie.png'),
('Finlande', 'finlande.png'),
('France', 'france.png'),
('Grèce', 'grece.png'),
('Hongrie', 'hongrie.png'),
('Irlande', 'irlande.png'),
('Italie', 'italie.png'),
('Lettonie', 'lettonie.png'),
('Lituanie', 'lituanie.png'),
('Luxembourg', 'luxembourg.png'),
('Malte', 'malte.png'),
('Pays-Bas', 'paysbas.png'),
('Pologne', 'pologne.png'),
('Portugal', 'portugal.png'),
('République tchèque', 'reptcheq.png'),
('Roumanie', 'roumanie.png'),
('Slovaquie', 'slovaquie.png'),
('Slovénie', 'slovenie.png'),
('Suède', 'suede.png');